name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [1.13, 1.16]
        stage: [testredis, testconn, testcluster]

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}

    - name: Cache redis build
      uses: actions/cache@v2
      with:
        path: |
          /tmp/redis-server
        key: ${{ runner.os }}-redis-${{ hashFiles('Makefile') }}

    - name: Install redis
      run: make /tmp/redis-server/redis-server


    - name: Build
      run: make ${{ matrix.stage }}

